# Workflow to run CIT on derecho via self-hosted runner

name: CIT on derecho w python script

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "feature_CIT" branch
  pull_request:
    types: [labeled]
    branches: 
      - develop
      - feature*
      - main*
      - bugfix_*
    paths-ignore:
      #- 'docs/**'
      - '.github/pull_request_template.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '**/README.md'
      - '**/LICENSE.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build_and_test"
  build_and_test:
    # Only do the actions when merged or manually run
    if: github.event.label.name == 'run-pr-tests' || github.event_name == 'workflow_dispatch'
    # The type of runner that the job will run on
    runs-on: shr-derecho

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it  v2 or v4? (Julie's example shows v2)
      - uses: actions/checkout@v4

      # Compile and run the FastEddy code via a python script
      - name: Run CompileRunFastEddy.py
        run: |
          cd ..
          ./CompileRunFastEddy.py -c derecho_cit.json

      # Run pytest on the results of the FastEddy run
      - name: Run pytest
        run: |
          source /glade/work/ishitas/python_envs/py_derecho/bin/activate
          pytest \
          --tb=no \
          --output-dir=/glade/work/fasteddyrt/actions-runner/_work/FastEddy-model/Example02_CBL/output_10steps \
          --ref-dir=/glade/work/fasteddyrt/actions-runner/_work/FastEddy-model/Example02_CBL/output_10steps \
          --html=report.html \
          --self-contained-html

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: /glade/work/fasteddyrt/actions-runner/_work/FastEddy-model/tests/report.html
      
      # Runs a simple scritpt that appends the datetime to a file
      - name: Record the datetime of the run
        run: |
          echo Append datetime to a file
          /glade/work/fasteddyrt/actions-runner/appendDatetimeRun.sh
          
